import { Post } from "./types";

// Real TikTok posts fetched via oEmbed. Thumbnails are TikTok CDN signed URLs
// (valid for ~7 days). Engagement numbers are estimates; replace with real data
// from the ingest script once yt-dlp is available.

export const MOCK_POSTS: Post[] = [
  // ─── GYM & STRENGTH ──────────────────────────────────────────────────────────
  {
    id: "tiktok:7469522451630951726",
    externalId: "7469522451630951726",
    clusterId: "gym",
    platform: "tiktok",
    handle: "@win_dle",
    displayName: "Kenley Windle",
    content: "Are you team @Gymshark or @Alphalete? 🫢 The LiftMiami event had everyone picking sides — here's what I actually think after trying both.",
    hashtags: ["#gymshark", "#alphalete", "#liftmiami", "#gymsharkwomen", "#fitness"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@win_dle/video/7469522451630951726",
    embedUrl: "https://www.tiktok.com/player/v1/7469522451630951726?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Gymshark vs Alphalete — LiftMiami",
      accent: "#7c6af7",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/og1DFChDRE3AcCMpEAAzEf69SEqsnIAPtDfRgX~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=iXk6qhcHZGQD3DjAjGOuc4UOsxE%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 121000,
    comments: 8400,
    shares: 44000,
    views: 820000,
    trendScore: 91,
    postedAt: "2d ago",
    whyTrending: {
      summary: "Brand loyalty debates are among the highest-engagement formats in fitness. Gymshark vs Alphalete is the defining rivalry of 2024–25 activewear — any creator taking a side triggers immediate mass comment activity.",
      signals: [
        { label: "Comment-to-view ratio", value: "1.02%", note: "Far above 0.3% average" },
        { label: "#gymshark weekly reach", value: "380M", note: "+190% WoW" },
        { label: "Brand reshare rate", value: "High", note: "Both brands amplifying" },
        { label: "Save rate", value: "5.4%", note: "Purchase-intent reference" },
      ],
      relatedHashtags: [
        { tag: "#gymshark", growth: "+190%" },
        { tag: "#alphalete", growth: "+175%" },
        { tag: "#gymwear", growth: "+210%" },
        { tag: "#fitness", growth: "+145%" },
      ],
    },
  },
  {
    id: "tiktok:6994935115000368390",
    externalId: "6994935115000368390",
    clusterId: "gym",
    platform: "tiktok",
    handle: "@jacked_paulus",
    displayName: "Jacked Paulus",
    content: "Who is actually more elite — Gymshark or Alphalete? I break down quality, fit, price and vibe so you don't have to guess.",
    hashtags: ["#gymshark", "#alphalete", "#clothes", "#gymtok", "#foryou"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@jacked_paulus/video/6994935115000368390",
    embedUrl: "https://www.tiktok.com/player/v1/6994935115000368390?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Gymshark vs Alphalete — who's more elite?",
      accent: "#7c6af7",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/19053fb45af5454f9c8b74e210f57dfe_1628635247~tplv-tiktokx-dmt-logom:tos-useast5-p-0068c799-tx/e98d271513014808a54ca360b3b03f82.image?dr=10393&x-expires=1779984000&x-signature=TadzhCzbkd4YkOf4rAIo31mkjgs%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 64000,
    comments: 11800,
    shares: 37000,
    views: 445000,
    trendScore: 84,
    postedAt: "3d ago",
    whyTrending: {
      summary: "Comparison content with a clear 'which is better' question drives the highest comment velocity on fitness TikTok. Gymshark and Alphalete have tribal fanbases — every opinion post becomes a debate thread.",
      signals: [
        { label: "Comment thread depth", value: "Avg 4.2 replies/comment", note: "Tribal debate pattern" },
        { label: "#gymtok weekly impressions", value: "520M", note: "Evergreen high-volume" },
        { label: "Brand mention pickup", value: "Both brands engaged", note: "Organic amplification" },
        { label: "Watch-through rate", value: "78%", note: "Strong completion" },
      ],
      relatedHashtags: [
        { tag: "#gymtok", growth: "+155%" },
        { tag: "#gymshark", growth: "+190%" },
        { tag: "#alphalete", growth: "+175%" },
        { tag: "#activewear", growth: "+130%" },
      ],
    },
  },
  {
    id: "tiktok:7058733500102413614",
    externalId: "7058733500102413614",
    clusterId: "gym",
    platform: "tiktok",
    handle: "@kimcasv",
    displayName: "Kim Vega",
    content: "Which gym brand do y'all actually recommend? I tested Alphalete, Gymshark and NVGTN for 30 days and here's my honest take.",
    hashtags: ["#gymtok", "#gymbrand", "#alphalete", "#gymshark", "#nvgtn"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@kimcasv/video/7058733500102413614",
    embedUrl: "https://www.tiktok.com/player/v1/7058733500102413614?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Best gym brand — Alphalete vs Gymshark vs NVGTN",
      accent: "#7c6af7",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/e1eeeb4df6c046bb9fdd6789af959aef_1643489467~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=baFeY0wtbGFnXNpMZzu769Yiv3g%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 41000,
    comments: 8900,
    shares: 21000,
    views: 278000,
    trendScore: 80,
    postedAt: "4d ago",
    whyTrending: {
      summary: "Three-way comparison expands the debate beyond the usual binary. NVGTN inclusion signals awareness of emerging brands challenging the incumbents. 'I tested for 30 days' framing adds credibility that drives saves.",
      signals: [
        { label: "Save rate", value: "7.6%", note: "Purchase-intent behaviour" },
        { label: "#nvgtn trending searches", value: "+340%", note: "Emerging brand interest" },
        { label: "Question-as-hook performance", value: "Strong", note: "Above-average open rate" },
        { label: "Comment sentiment", value: "84% brand opinions", note: "High engagement quality" },
      ],
      relatedHashtags: [
        { tag: "#gymshark", growth: "+190%" },
        { tag: "#nvgtn", growth: "+340%" },
        { tag: "#gymwear", growth: "+210%" },
        { tag: "#gymbrand", growth: "+180%" },
      ],
    },
  },
  {
    id: "tiktok:7377488310245068064",
    externalId: "7377488310245068064",
    clusterId: "gym",
    platform: "tiktok",
    handle: "@allymcclayfits",
    displayName: "Ally McClay",
    content: "Matching gym outfits 🫶 Which brand takes the W — Gymshark, DFYNE or Alphalete? Full try-on comparison.",
    hashtags: ["#gymshark", "#dfyne", "#alphalete", "#gymfit", "#gymwear"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@allymcclayfits/video/7377488310245068064",
    embedUrl: "https://www.tiktok.com/player/v1/7377488310245068064?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Matching gym outfits — Gymshark vs DFYNE vs Alphalete",
      accent: "#7c6af7",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-no1a-p-0037c700-no/c5fee6e97d5b4a9cb92e986e0d8d1565_1717705381~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=V5FtHGHyWjJx7VP7Hq8wGP2pZCw%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 94000,
    comments: 7100,
    shares: 54000,
    views: 650000,
    trendScore: 88,
    postedAt: "1d ago",
    whyTrending: {
      summary: "Try-on haul format with a direct brand comparison is the highest-performing content type in women's activewear. DFYNE inclusion signals creator awareness of challenger brands — both brand communities engage heavily.",
      signals: [
        { label: "Share-to-view ratio", value: "8.3%", note: "Viral velocity signal" },
        { label: "#dfyne search spike", value: "+280%", note: "Emerging brand breakout" },
        { label: "Brand accounts reposted", value: "2 of 3 brands shared", note: "Earned distribution" },
        { label: "Watch-through", value: "85%", note: "Outfit reveal format holds" },
      ],
      relatedHashtags: [
        { tag: "#gymshark", growth: "+190%" },
        { tag: "#dfyne", growth: "+280%" },
        { tag: "#alphalete", growth: "+175%" },
        { tag: "#gymfit", growth: "+145%" },
      ],
    },
  },
  {
    id: "tiktok:7248453209751325998",
    externalId: "7248453209751325998",
    clusterId: "gym",
    platform: "tiktok",
    handle: "@charlsieeelifts",
    displayName: "Charlsie",
    content: "Hawaii gym fit check 🌺 Rocking R1P graphic tee, Gymshark adapt camo and Alphalete tank — which outfit wins?",
    hashtags: ["#hawaii", "#gymtok", "#fyp", "#gymshark", "#alphalete"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@charlsieeelifts/video/7248453209751325998",
    embedUrl: "https://www.tiktok.com/player/v1/7248453209751325998?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Hawaii gym fit check — R1P, Gymshark, Alphalete",
      accent: "#7c6af7",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/540344b7b1174f3db803415e94c1a84f~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=80upmwzNEDzVJLNwozCY5wOGAmw%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 27000,
    comments: 4800,
    shares: 17000,
    views: 188000,
    trendScore: 76,
    postedAt: "5d ago",
    whyTrending: {
      summary: "Location + gym lifestyle crossover (Hawaii + fitness) creates aspirational lifestyle content that performs above pure workout posts. Three-brand showcase introduces R1P to audiences primarily familiar with Gymshark/Alphalete.",
      signals: [
        { label: "Lifestyle-gym crossover score", value: "High", note: "Aspirational travel-fit blend" },
        { label: "#r1p brand searches", value: "+190%", note: "Emerging brand discovery" },
        { label: "Comment type", value: "68% 'where to buy'", note: "Commerce intent" },
        { label: "Saves", value: "9,200", note: "Reference behaviour" },
      ],
      relatedHashtags: [
        { tag: "#gymtok", growth: "+155%" },
        { tag: "#gymshark", growth: "+190%" },
        { tag: "#gymfit", growth: "+145%" },
        { tag: "#fitcheck", growth: "+120%" },
      ],
    },
  },

  // ─── TECH & CREATOR ECONOMY ───────────────────────────────────────────────────
  {
    id: "tiktok:7505118171075071237",
    externalId: "7505118171075071237",
    clusterId: "tech",
    platform: "tiktok",
    handle: "@tiffintech",
    displayName: "Tiff in Tech",
    content: "As AI keeps getting better, will coding become a thing of the past? And what other skills will no longer be required? This is the debate nobody wants to have honestly.",
    hashtags: ["#tech", "#technology", "#stem", "#ai", "#coding"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@tiffintech/video/7505118171075071237",
    embedUrl: "https://www.tiktok.com/player/v1/7505118171075071237?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Will AI replace coding? — Tiff in Tech",
      accent: "#69c9d0",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-maliva-p-0068/o0CDoOEoErAi3ieiAoIi9EvZAJB2gBAIMAT0zn~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=d47oENYVal0y2Je5rH62X4Z5cnk%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 178000,
    comments: 24600,
    shares: 91000,
    views: 1200000,
    trendScore: 95,
    postedAt: "18h ago",
    whyTrending: {
      summary: "AI vs human skills is the defining anxiety of 2025. A STEM creator asking the question that developers fear most generates peak comment volume — every software engineer has an opinion and needs to share it.",
      signals: [
        { label: "Comment velocity", value: "24,600 in 18h", note: "Extremely high debate rate" },
        { label: "#ai weekly reach", value: "2.1B", note: "Dominant trending topic" },
        { label: "Developer account shares", value: "High", note: "Professional amplification" },
        { label: "Watch-through rate", value: "92%", note: "High-stakes question hook" },
      ],
      relatedHashtags: [
        { tag: "#ai", growth: "+420%" },
        { tag: "#coding", growth: "+280%" },
        { tag: "#tech", growth: "+195%" },
        { tag: "#stem", growth: "+160%" },
      ],
    },
  },
  {
    id: "tiktok:7410382147959278855",
    externalId: "7410382147959278855",
    clusterId: "tech",
    platform: "tiktok",
    handle: "@tech_updt",
    displayName: "Tech Update",
    content: "MKBHD is the undisputed king of tech YouTube. Here's why no one even comes close in 2024.",
    hashtags: ["#mkbhd", "#mrwhosetheboss", "#fyp", "#techyoutuber"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@tech_updt/video/7410382147959278855",
    embedUrl: "https://www.tiktok.com/player/v1/7410382147959278855?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "MKBHD — king of tech YouTube",
      accent: "#69c9d0",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-alisg-p-0037/oUEGQUNfv0aIWLCVq91m4BFccBYDMfgBA91pWB~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=kL9UzYOpHRq8pJZjt5yuxHFastA%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 54000,
    comments: 7800,
    shares: 39000,
    views: 348000,
    trendScore: 82,
    postedAt: "2d ago",
    whyTrending: {
      summary: "Creator ranking content drives outsized engagement because audiences feel personally invested in their favourites. MKBHD's dominance is debated but widely accepted — 'undisputed' framing invites counter-arguments that fuel the comment section.",
      signals: [
        { label: "#mkbhd search volume", value: "+165%", note: "Spike after product review" },
        { label: "Reply chain depth", value: "Avg 6 replies", note: "Long debate threads" },
        { label: "Cross-platform shares", value: "High", note: "Tech Twitter amplification" },
        { label: "New follower spike", value: "+8,200 in 48h", note: "Creator discovery" },
      ],
      relatedHashtags: [
        { tag: "#mkbhd", growth: "+165%" },
        { tag: "#techyoutuber", growth: "+210%" },
        { tag: "#mrwhosetheboss", growth: "+145%" },
        { tag: "#tech", growth: "+195%" },
      ],
    },
  },
  {
    id: "tiktok:7279020516990553390",
    externalId: "7279020516990553390",
    clusterId: "tech",
    platform: "tiktok",
    handle: "@podcastcollective_",
    displayName: "Podcast Collective",
    content: "Mrwhosetheboss just called MKBHD the no.1 tech YouTuber — the tech community completely lost it.",
    hashtags: ["#mkbhd", "#mrwhosetheboss", "#colinandsamir", "#tech", "#techyoutuber", "#apple"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@podcastcollective_/video/7279020516990553390",
    embedUrl: "https://www.tiktok.com/player/v1/7279020516990553390?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Mrwhosetheboss endorses MKBHD as #1 tech creator",
      accent: "#69c9d0",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/3e1f8416cbcd46709836f56b0cd845d2_1694779097~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=yTSYH3QxZwWPIZvYyJSaIk%2BiPmU%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 124000,
    comments: 17900,
    shares: 76000,
    views: 815000,
    trendScore: 90,
    postedAt: "1d ago",
    whyTrending: {
      summary: "Creator-endorsing-creator content is the highest-velocity format in the tech community. When Mrwhosetheboss validates MKBHD publicly, it triggers every fan of both to stake a position — creating a self-sustaining debate loop.",
      signals: [
        { label: "Cross-creator fan overlap", value: "High", note: "Both audiences activated" },
        { label: "#colinandsamir search spike", value: "+230%", note: "Third creator pulled in" },
        { label: "Podcast clip saves", value: "14.8%", note: "Reference-watch behaviour" },
        { label: "Share velocity (6h)", value: "22K shares", note: "Rapid amplification" },
      ],
      relatedHashtags: [
        { tag: "#mkbhd", growth: "+165%" },
        { tag: "#mrwhosetheboss", growth: "+145%" },
        { tag: "#colinandsamir", growth: "+230%" },
        { tag: "#techyoutuber", growth: "+210%" },
      ],
    },
  },
  {
    id: "tiktok:7395910891918691590",
    externalId: "7395910891918691590",
    clusterId: "tech",
    platform: "tiktok",
    handle: "@top5_r1",
    displayName: "Top 5 Rankings",
    content: "Mr. Beast vs MKBHD — who is actually bigger in 2024? The numbers will shock you.",
    hashtags: ["#mkbhd", "#mrwhosetheboss", "#foryou", "#techyoutuber"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@top5_r1/video/7395910891918691590",
    embedUrl: "https://www.tiktok.com/player/v1/7395910891918691590?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Mrwhosetheboss vs MKBHD — who's bigger?",
      accent: "#69c9d0",
      url: "https://p19-common-sign.tiktokcdn-eu.com/tos-maliva-p-0068/ooEQjmfEVB4woQR74SIAGFEB1jDPPoAanf5vcJ~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=Pn3Bpt8Fgl3B2RenLiPZl3bErEA%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 71000,
    comments: 13500,
    shares: 51000,
    views: 478000,
    trendScore: 85,
    postedAt: "2d ago",
    whyTrending: {
      summary: "YouTuber ranking content dominates TikTok because the platform's audience uses it to discover creators. 'Numbers will shock you' mystery hook drives full watch-through. Two distinct fanbases collide in comments.",
      signals: [
        { label: "Fan camp ratio", value: "52/48 split", note: "Evenly contested" },
        { label: "Watch-through rate", value: "88%", note: "Mystery hook effective" },
        { label: "Profile visits from video", value: "+12,400", note: "Discovery driver" },
        { label: "#foryou placement rate", value: "Very high", note: "Algorithm favourite" },
      ],
      relatedHashtags: [
        { tag: "#mkbhd", growth: "+165%" },
        { tag: "#techyoutuber", growth: "+210%" },
        { tag: "#mrwhosetheboss", growth: "+145%" },
        { tag: "#foryoupage", growth: "+95%" },
      ],
    },
  },
  {
    id: "tiktok:7636300127145118989",
    externalId: "7636300127145118989",
    clusterId: "tech",
    platform: "tiktok",
    handle: "@tech.gadgets.368",
    displayName: "Tech Gadgets 368",
    content: "The first truly smart glasses that actually work — and they're from OnePlus. Full review and reaction.",
    hashtags: ["#smartglasses", "#oneplus", "#phone", "#review", "#techgadgets"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@tech.gadgets.368/video/7636300127145118989",
    embedUrl: "https://www.tiktok.com/player/v1/7636300127145118989?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "OnePlus smart glasses — full review",
      accent: "#69c9d0",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast5-p-0068-tx/o0mC7fBPzimtAApOO00KIPwWWiELvBgBI5luEO~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=ryky0mZAF3k7vBWahZQRqoaT7FQ%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 23000,
    comments: 3900,
    shares: 14000,
    views: 159000,
    trendScore: 74,
    postedAt: "6h ago",
    whyTrending: {
      summary: "Smart glasses are the most anticipated consumer tech category of 2025. Any 'first review' claim triggers massive early-adopter attention. OnePlus entering a category dominated by Meta Ray-Ban is a genuine news moment.",
      signals: [
        { label: "#smartglasses search volume", value: "+480%", note: "Meta Ray-Ban halo effect" },
        { label: "Tech media pickup", value: "3 outlets shared", note: "Cross-platform" },
        { label: "Early watch spikes", value: "6h velocity high", note: "Fresh content premium" },
        { label: "Save rate", value: "8.7%", note: "Want-to-watch-later" },
      ],
      relatedHashtags: [
        { tag: "#smartglasses", growth: "+480%" },
        { tag: "#oneplus", growth: "+290%" },
        { tag: "#techreview", growth: "+165%" },
        { tag: "#gadgets", growth: "+140%" },
      ],
    },
  },

  // ─── FASHION & STYLE ─────────────────────────────────────────────────────────
  {
    id: "tiktok:7489148112913616159",
    externalId: "7489148112913616159",
    clusterId: "fashion",
    platform: "tiktok",
    handle: "@dianakonfederat",
    displayName: "Diana Konfederat",
    content: "A moment for this t-shirt 🤍 I love a good Zara find — styled it with Mango for the perfect spring look. Full outfit details in comments.",
    hashtags: ["#zara", "#zarahaul", "#springfashion", "#chanel", "#ootd", "#whatimwearing"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@dianakonfederat/video/7489148112913616159",
    embedUrl: "https://www.tiktok.com/player/v1/7489148112913616159?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "Zara × Mango spring OOTD — Diana Konfederat",
      accent: "#e1306c",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-useast8-p-0068-tx2/osDivzHJEP3CKI9BMuPBfiAIZJAiAA2AAabzIL~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=4WGXg8T9Kc5HDnnZfXVmKuMzWsk%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 318000,
    comments: 27400,
    shares: 143000,
    views: 2100000,
    trendScore: 96,
    postedAt: "14h ago",
    whyTrending: {
      summary: "Zara + accessible luxury pairing is the dominant fashion formula on TikTok in 2025. Diana's ability to make high-street look editorial drives massive aspiration. Spring haul timing aligns with peak fashion purchase intent.",
      signals: [
        { label: "#zarahaul weekly reach", value: "640M", note: "+320% WoW, spring spike" },
        { label: "Link-in-bio clicks", value: "+1,840%", note: "Purchase conversion surge" },
        { label: "Comment type", value: "71% 'where to buy'", note: "Commerce intent" },
        { label: "Brand reshare", value: "Zara official reposted", note: "Brand amplification" },
      ],
      relatedHashtags: [
        { tag: "#zarahaul", growth: "+320%" },
        { tag: "#springfashion", growth: "+285%" },
        { tag: "#ootd", growth: "+195%" },
        { tag: "#zara", growth: "+240%" },
      ],
    },
  },
  {
    id: "tiktok:7524788164637003064",
    externalId: "7524788164637003064",
    clusterId: "fashion",
    platform: "tiktok",
    handle: "@richelle_zh",
    displayName: "Richelle",
    content: "My algorithm knows me so well 😭 Every outfit on my FYP is exactly my vibe right now — here's what I've been wearing.",
    hashtags: ["#fashion", "#outfit", "#myoutfit", "#style", "#ootd", "#inspo", "#fyp"],
    isVideo: true,
    sourceUrl: "https://www.tiktok.com/@richelle_zh/video/7524788164637003064",
    embedUrl: "https://www.tiktok.com/player/v1/7524788164637003064?controls=1&description=0&music_info=0",
    thumbnail: {
      label: "FYP outfit inspo — algorithm knows best",
      accent: "#e1306c",
      url: "https://p16-common-sign.tiktokcdn-eu.com/tos-alisg-p-0037/oAeeBv0fEiJgI43GCBSAiCc4EorNAcUlJDKTjJ~tplv-tiktokx-origin.image?dr=10395&x-expires=1779984000&x-signature=dUPECnYdHcD%2BODo3mGft5ogadpM%3D&t=4d5b0474&ps=13740610&shp=81f88b70&shcp=43f4a2f9&idc=no1a",
    },
    likes: 141000,
    comments: 15700,
    shares: 97000,
    views: 890000,
    trendScore: 92,
    postedAt: "20h ago",
    whyTrending: {
      summary: "Algorithm-as-identity content is the breakout fashion format of 2025. Viewers relate to being 'understood' by their FYP — this creates instant connection. Multiple-outfit format maximises watch time while the relatability hook drives shares.",
      signals: [
        { label: "Share-to-view ratio", value: "10.9%", note: "Top 0.2% of fashion posts" },
        { label: "#ootd FYP placement", value: "Algorithm-boosted", note: "High relevance signal" },
        { label: "Creator DMs after post", value: "+4,200", note: "Styling enquiries" },
        { label: "Saves", value: "38,000", note: "Inspo board behaviour" },
      ],
      relatedHashtags: [
        { tag: "#ootd", growth: "+195%" },
        { tag: "#outfitinspo", growth: "+270%" },
        { tag: "#fashion", growth: "+155%" },
        { tag: "#fyp", growth: "+110%" },
      ],
    },
  },
];
